version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: xscan-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: xscan
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - xscan-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: xscan-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - xscan-network

  # NestJS Backend
  backend:
    build: .
    container_name: xscan-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongodb:27017/xscan?authSource=admin
      MONGODB_DB_NAME: xscan
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      REDIS_DB: 0
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
      UPLOAD_DIR: uploads
      MAX_FILE_SIZE: 10485760
      BASE_URL: http://localhost:3001
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    networks:
      - xscan-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
  redis_data:

networks:
  xscan-network:
    driver: bridge 